params:
  seed: ${...seed}

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: orthogonal_initializer
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [{'pi': [512], 'vf': [512]}] #[400, 200, 100]
      activation: elu
      d2rl: False
      
      initializer:
        name: orthogonal_initializer
      regularizer:
        name: None


    feature_extractor:
      type: encode_concat
      feature_mlp:
        units: [512, 256, 128] #[400, 200, 100]
        activation: elu
      encode_concat:
        units: [128, 128, 128] #[400, 200, 100]
        activation: elu

    lstm:
      hidden_size: 512
      n_layers: 1

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:BlindHumanoid,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    device: ${....rl_device}
    device_name: ${....rl_device}
    multi_gpu: False
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: False
    value_bootstrap: False
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 0.01
      min_val: -1e12
      max_val: 1e12
    norm_reward: False
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: ${resolve_default:1000,${....max_iterations}}
    save_best_after: 100
    save_frequency: 5 #[default: 100]
    grad_norm: 1.0
    entropy_coef: 0.01
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 32 # [default: 32]
    n_mini_batch: 4
    # minibatch_size: 32768
    mini_epochs: 5
    critic_coef: 2
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0001
    enable_curiosity: False
    curiosity_beta: 10.0
    curiosity_foward_weight: 0.2
    enable_ema: False
    ema_weight: 1.0
    pretrain_walking: False
      
